[platformio]
default_envs = epd_398_jd79665_c3_promini

[common]
platform = espressif32@6.10.0
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_4mb_gallery.csv
board_build.filesystem = littlefs
board_build.extra_flags =
extra_scripts = post:merge_firmware.py

# ── 3.98" 768x552 BWRY (JD79665) 屏 软件模拟SPI驱动 ────────────────────────────
[env:epd_398_jd79665_c3_promini]
extends = common
board = esp32-c3-devkitm-1
build_flags =
    -DBOARD_PROFILE_ESP32_C3_HUAWEI
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DEPD_WIDTH=768
    -DEPD_HEIGHT=552
    -DEPD_PANEL_JD79665
    -DEPD_BPP=2
    -DALLOW_INSECURE_FALLBACK=0

[env:epd_398_jd79665_c3_std]
extends = common
board = esp32-c3-devkitm-1
upload_speed = 460800
board_build.flash_mode = dio
board_build.f_flash = 40000000L
build_flags =
    -DBOARD_PROFILE_ESP32_C3_HUAWEI
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DEPD_WIDTH=768
    -DEPD_HEIGHT=552
    -DEPD_PANEL_JD79665
    -DEPD_BPP=2
    -DALLOW_INSECURE_FALLBACK=0
